### ISSUE TITLE
Little uncertain about dataReactions

### ISSUE THREAD

**Issue by kurtharriger** [winstonewert/redux-reactions#5]
I'm not sure if this is intended to be part of the reactions api or an attempt to remove duplication between Repo and User pages.  

I think maybe it would be better to hide dataReactions and expose preconfigured userDataReactions and a repoDataReactions that know the appropriate fetch methods.

**Comment by kurtharriger** [comment]
maybe even follow a mapStateToProps pattern for to convert app state to reaction state?

**Comment by winstonewert** [comment]
To my mind, this was a mapStateToProps pattern, the reactions function take the state and returns reactions like how mapStateToProps takes the state and returns the props.

It's not part of the reactions api, just an attempt to remove duplication between those pages.

I considered exporting the preconfigured versions, I hesitate because it seems more related to the param interpretation done in the individual components.
